# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import service.server.servicer_pb2 as servicer__pb2


class ServicerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetSerializationTime = channel.unary_unary(
                '/Servicer/GetSerializationTime',
                request_serializer=servicer__pb2.Query.SerializeToString,
                response_deserializer=servicer__pb2.SerializationResponse.FromString,
                )


class ServicerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetSerializationTime(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ServicerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetSerializationTime': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSerializationTime,
                    request_deserializer=servicer__pb2.Query.FromString,
                    response_serializer=servicer__pb2.SerializationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Servicer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Servicer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetSerializationTime(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Servicer/GetSerializationTime',
            servicer__pb2.Query.SerializeToString,
            servicer__pb2.SerializationResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
