# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: servicer.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eservicer.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"h\n\x15SerializationResponse\x12\x0e\n\x06typeId\x18\x01 \x01(\x03\x12\x0f\n\x07objSize\x18\x02 \x01(\x03\x12\x15\n\rserializeTime\x18\x03 \x01(\x01\x12\x17\n\x0f\x64\x65serializeTime\x18\x04 \x01(\x01\"\x17\n\x05Query\x12\x0e\n\x06typeId\x18\x01 \x01(\x03\x32\x44\n\x08Servicer\x12\x38\n\x14GetSerializationTime\x12\x06.Query\x1a\x16.SerializationResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'servicer_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SERIALIZATIONRESPONSE._serialized_start=51
  _SERIALIZATIONRESPONSE._serialized_end=155
  _QUERY._serialized_start=157
  _QUERY._serialized_end=180
  _SERVICER._serialized_start=182
  _SERVICER._serialized_end=250
# @@protoc_insertion_point(module_scope)
